#!/bin/zsh
source "${0:a:h}/../functions"

[ ! $AWS_PROFILE ] && { echo 'AWS_PROFILE required'; exit 1; }

#####################################################################

USER=$(GET_USERS | fzf --reverse --prompt 'Select a user: ')
[ ! $USER ] && exit 2

ARN=$(\
    aws --profile $AWS_PROFILE iam list-attached-user-policies \
        --user-name $USER \
        | awk '{print $2;}' \
        | fzf --reverse --prompt 'Select a policy to detach: '
)
[ ! $ARN ] && exit 2


echo "USER :: $USER"
echo "ARN  :: $ARN"
printf "Really detach the policy to the listed user? [yN]"
read -k yn
echo

[[ $yn =~ ^[yY]$ ]] || { echo aborting; exit 1 }

aws --profile $AWS_PROFILE iam detach-user-policy \
    --user-name "$USER" \
    --policy-arn "$ARN" \
    ;
