CREATE USER rd WITH PASSWORD 'test1234';
CREATE USER rentplus WITH PASSWORD 'test1234';
CREATE USER textmsgit WITH PASSWORD 'test1234';
CREATE USER chat WITH PASSWORD 'test1234';
CREATE USER rdemail WITH PASSWORD 'test1234';

ALTER USER rd WITH SUPERUSER;
ALTER USER rentplus WITH SUPERUSER;
ALTER USER textmsgit WITH SUPERUSER;
ALTER USER chat WITH SUPERUSER;
ALTER USER rdemail WITH SUPERUSER;

CREATE DATABASE rentdynamics WITH OWNER rd;
CREATE DATABASE rentplus WITH OWNER rd;
CREATE DATABASE textmsgit WITH OWNER textmsgit;
CREATE DATABASE chat WITH OWNER chat;
