#####################################################################
### RENT DYNAMICS REQUIRED FIELDS ###################################
#####################################################################
#                                                                   #
# warning : do not edit this file; it is overwritten regularly!     #
#           if you need to overwrite a variable, provide the envvar #
#           RD_CUSTOM_CONFIG_FILE which exports your overrides      #
#                                                                   #
# protip  : don't provide an override file unless you're an expert  #
#                                                                   #
#####################################################################

export RD_MY_FIRST_NAME=
export RD_MY_LAST_NAME=
export RD_MY_EMAIL_ADDRESS=
export RD_TOOLS_BUILD_DIR=

#####################################################################

export RD_PATH="$HOME/RentDynamics"
export RD_SECRET_PROFILE="rd.${RD_MY_LAST_NAME:l}-${RD_MY_FIRST_NAME:l}"
export RD_SCRIPTS_LIBRARY="$RD_TOOLS_BUILD_DIR/wryipts"
export RD_ZSH_PLUGIN="$RD_TOOLS_BUILD_DIR/zsh-plugin"
export RD_TOOLS_BIN="$RD_TOOLS_BUILD_DIR/bin"

#####################################################################

export CLICOLOR=1
which vim >/dev/null 2>&1 && export EDITOR=$(which vim)

FZF_DEFAULT_OPTS='--reverse'
FZF_DEFAULT_COMMAND='rg --files'
zstyle ':fzf-tab:*' accept-line enter
zstyle ':fzf-tab:*' fzf-bindings 'space:accept' ';:toggle'
zstyle ':fzf-tab:*' continuous-trigger '/'

export STARSHIP_CONFIG="$RD_SCRIPTS_LIBRARY/setup/config/starship.toml"

#####################################################################

[ $RD_CUSTOM_CONFIG_FILE ] \
	&& [ -f $RD_CUSTOM_CONFIG_FILE ] && source $RD_CUSTOM_CONFIG_FILE

#####################################################################

