#!/bin/zsh
source "${0:a:h}/functions"

#####################################################################

[ ! $AWS_RD_CREDENTIALS_DIR ] && { STAGE_ENV_VAR 'AWS_RD_CREDENTIALS_DIR'; ERROR=1; }

USERNAMES_FILE="$AWS_RD_CREDENTIALS_DIR/users"
[ ! -f $USERNAMES_FILE ] && { echo '$AWS_RD_CREDENTIALS_DIR/users required'; ERROR=2; }

[ $ERROR ] && exit $ERROR

#####################################################################

while read line
do
	username=$(echo $line | awk '{print $1;}')
	serial=$(echo $line | awk '{print $2;}')

	USER_EXISTS $username && {
		echo "'$username' already exists; ignoring."
	} || {
		echo "Setting up '$username'..."
		CREATE_USER $username
		CREATE_ACCESS_KEY $username || ROTATE_USER_CREDENTIALS $username
	}

	SYNC_USER_SERIAL $username $serial

done < $USERNAMES_FILE
