#!/bin/zsh
source "${0:a:h}/functions"

#####################################################################

[ ! $AWS_RD_CREDENTIALS_DIR ] && { STAGE_ENV_VAR 'AWS_RD_CREDENTIALS_DIR'; ERROR=1; }

USERNAMES_FILE="$AWS_RD_CREDENTIALS_DIR/users"
[ ! -f $USERNAMES_FILE ] && { echo '$AWS_RD_CREDENTIALS_DIR/users required'; ERROR=2; }

[ $ERROR ] && exit $ERROR

#####################################################################

username=$(awk '{print $1;}' $USERNAMES_FILE | fzf ${FZF_OPTIONS[@]} --prompt 'Select a user : ')

serial=$(grep $username $USERNAMES_FILE | awk '{print $2;}')
serial=$(echo $line | awk '{print $2;}')

echo $username
echo $serial

exit 1

ROTATE_USER_CREDENTIALS $username $serial

exit 0
