#!/bin/zsh
source "${0:a:h}/../functions"

[ ! $AWS_PROFILE ] && { echo 'AWS_PROFILE required'; exit 1; }

#####################################################################

ROLE=$(GET_ROLES | fzf --reverse --prompt 'Select a role: ')
[ ! $ROLE ] && exit 2

ARN=$(\
    echo $RD_POLICIES | awk '{print $2;}' \
        | fzf --reverse --prompt 'Select a policy to attach: '
)
[ ! $ARN ] && exit 2


echo "ROLE :: $ROLE"
echo "ARN  :: $ARN"
printf "Really attach the policy to the listed role? [yN]"
read -k yn
echo

[[ $yn =~ ^[yY]$ ]] || { echo aborting; exit 1 }

aws --profile $AWS_PROFILE iam attach-role-policy \
    --role-name "$ROLE" \
    --policy-arn "$ARN" \
    ;
